"""empty message

Revision ID: 5d8f0b257b1c
Revises: b97b9076b98f
Create Date: 2023-11-28 13:08:11.798796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d8f0b257b1c'
down_revision = 'b97b9076b98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=80),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=80),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
