"""Modify tables after correcting errors in api

Revision ID: 86e4fb11588e
Revises: 0fd034f5b544
Create Date: 2023-10-17 23:02:14.454915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86e4fb11588e'
down_revision = '0fd034f5b544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'promotion', ['promotion'], ['name'])
        batch_op.create_foreign_key(None, 'ressources', ['ressources'], ['name'])
        batch_op.create_foreign_key(None, 'enseignant', ['enseignant'], ['initial'])
        batch_op.create_foreign_key(None, 'groupe', ['groupe'], ['idGroupe'])
        batch_op.create_foreign_key(None, 'salle', ['salle'], ['nom'])
        batch_op.drop_column('ressource')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ressource', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
