"""Initial migration

Revision ID: a5737583c007
Revises: 
Create Date: 2023-10-13 11:24:09.373192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5737583c007'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=False))
        batch_op.drop_index('identifiant')
        batch_op.create_unique_constraint(None, ['identifier'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('identifiant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifiant', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('identifiant', ['identifiant'], unique=False)
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')
        batch_op.drop_column('role')
        batch_op.drop_column('password')
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###
