"""Modify tables after correcting errors in api

Revision ID: a84c4d225b10
Revises: 86e4fb11588e
Create Date: 2023-10-17 23:05:37.811411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a84c4d225b10'
down_revision = '86e4fb11588e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'salle', ['salle'], ['nom'])
        batch_op.create_foreign_key(None, 'groupe', ['groupe'], ['idGroupe'])
        batch_op.create_foreign_key(None, 'ressources', ['ressources'], ['name'])
        batch_op.create_foreign_key(None, 'enseignant', ['enseignant'], ['initial'])
        batch_op.drop_column('ressource')

    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.drop_index('cours_ibfk_2_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.create_index('cours_ibfk_2_index', ['name'], unique=False)

    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ressource', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
