"""Modify tables after correcting errors in api

Revision ID: aa6dce761183
Revises: b0c1c1d72b3a
Create Date: 2023-10-17 23:15:21.729679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6dce761183'
down_revision = 'b0c1c1d72b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.drop_index('cours_ibfk_2_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.create_index('cours_ibfk_2_index', ['name'], unique=False)

    # ### end Alembic commands ###
