"""Modify tables after correcting errors in api

Revision ID: b0c1c1d72b3a
Revises: a84c4d225b10
Create Date: 2023-10-17 23:06:36.387966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c1c1d72b3a'
down_revision = 'a84c4d225b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'salle', ['salle'], ['nom'])

    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.drop_index('cours_ibfk_2_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.create_index('cours_ibfk_2_index', ['name'], unique=False)

    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
