"""Correction of tables and adding of new ones

Revision ID: b97b9076b98f
Revises: 876abbc02950
Create Date: 2023-11-17 12:11:38.063318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b97b9076b98f'
down_revision = '876abbc02950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RespEDTPromo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respEdt', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('promotion', sa.String(length=64), nullable=False))
        batch_op.drop_constraint('RespEDTPromo_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('RespEDTPromo_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'promotion', ['promotion'], ['name'])
        batch_op.create_foreign_key(None, 'user', ['respEdt'], ['identifier'])
        batch_op.drop_column('RespEdt')
        batch_op.drop_column('Promotion')

    with op.batch_alter_table('groupe', schema=None) as batch_op:
        batch_op.alter_column('groupeTd',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('groupeTp',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groupe', schema=None) as batch_op:
        batch_op.alter_column('groupeTp',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('groupeTd',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('RespEDTPromo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Promotion', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('RespEdt', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('RespEDTPromo_ibfk_2', 'promotion', ['Promotion'], ['name'])
        batch_op.create_foreign_key('RespEDTPromo_ibfk_1', 'user', ['RespEdt'], ['identifier'])
        batch_op.drop_column('promotion')
        batch_op.drop_column('respEdt')

    # ### end Alembic commands ###
