"""Correcting errors between api and database

Revision ID: e7a9717cf197
Revises: aa6dce761183
Create Date: 2023-10-17 23:18:10.742111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a9717cf197'
down_revision = 'aa6dce761183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.drop_constraint('cours_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ressources', ['ressource'], ['initial'])

    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.drop_index('cours_ibfk_2_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.create_index('cours_ibfk_2_index', ['name'], unique=False)

    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cours_ibfk_2', 'ressources', ['ressource'], ['name'])

    # ### end Alembic commands ###
